<header>
    <nav class="teal lighten-2">
        <div class="nav-wrapper">
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="/">Home</a></li>
                <li><a href="/texto">Texto</a></li>
            </ul>
        </div>
        <ul class="sidenav" id="mobile-demo">
            <li><a href="/">Home</a></li>
            <li><a href="/texto">Texto</a></li>
        </ul>
    </nav>
</header>