<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		<div class="col-md-3">
			<div class="perfil">
				<div class="perfilTopo">
				</div>
				<?php include_once '../App/Src/Views/decompose/perfilpainel.phtml'; ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="/quemseguir" method="POST">
								<div class="input-group mb-3">
									<input type="text" class="form-control" placeholder="Quem você está procurando?" name="nome">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<?php
                                if (!isset($_POST['nome'])) {
                                    return false;
                                }

                                foreach ($usuario->procurarUsuarios() as $user) {
                                    if ($user['id'] != $_SESSION['id']) { ?>
										<div class="row mb-2">
											<div class="col">
												<div class="card">
													<div class="card-body">
														<div class="row">
															<div class="col-md-6">
																<?=$user['nome']?>
															</div>
															<div class="col-md-6 d-flex justify-content-end">
																<?php if ($user['id_usuario'] == $_SESSION['id']) { ?>
																	<div>
																		<a href="/unfollow/<?=$user['nome']?>" class="btn btn-danger">Deixar de seguir</a>
																	</div>
																<?php } else { ?>
																	<div>
																		<a href="/follow/<?=$user['nome']?>" class="btn btn-success">Seguir</a>
																	</div>
																<?php } ?>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									<?php }
                                } ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>