<?php
	if(!isset($_SESSION['id']) || !isset($_SESSION['nome']))
		header('Location: /');
?>

<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>
	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>
<div class="container mt-5">
	<div class="row pt-2">
		<div class="col-md-3">
			<div class="perfil">
				<div class="perfilTopo">
				</div>
				<?php include_once '../App/Src/Views/decompose/perfilpainel.phtml'; ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="POST">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet" minlength="3"></textarea>
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>
						<?php if(isset($_GET['tweet']) && $_GET['tweet'] == 'success') { ?>
							<small class="text text-success">Tweet criado!</small>
						<?php } ?>
					</form>
				</div>
			</div>
			<?php foreach($usuario->getAllTweets() as $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?=$tweet['nome']?></strong> <span class="text text-muted"><small> - <?=$tweet['data']?></small></span></p>
						<p><?=$tweet['tweet']?></p>
						<br />
						<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?>
							<form action="/removetweet" method="POST">
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger" value="<?=base64_encode($tweet['id'])?>" name="id"><small>Remover</small></button>
									<input type="hidden"></input>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
		</div>
		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemseguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>
	</div>
</div>