<script>
    // Variable data are use by autocomplete
    let books = JSON.parse('<?=json_encode($var['books'])?>')
    let data = {}

    for (let book in books) {
        data[book] = null
    }
</script>

<main>
    <section class="container" id="search">
        <div class="row">
            <div class="col s12 m6">
                <h2>Texto</h2>
                <form action="">
                    <select name="text" class="browser-default">
                        <option disabled selected>- Selecione -</option>
                        <?php foreach ($var['books'] as $key => $value): ?>
                            <optgroup label="<?= $key ?>">
                            <?php foreach ($value as $subKey => $text): ?>
                                <option value="<?=$text['path']?>"><?=$subKey?></option>
                            <?php endforeach ?>
                            </optgroup>
                        <?php endforeach ?>
                    </select>
                    <button class="btn waves-effect waves-light" type="submit">Procurar<i class="material-icons right">search</i></button>
                </form>
            </div>
        </div>
    </section>
    <section class="container">
        <div class="row">
            <div class="col s12">
                <form action="" method="POST">
                    <div class="input-field">
                        <input type="text" name="book" id="autocomplete-input" class="autocomplete" value="<?=$var['info']['book']?>">
                        <label for="autocomplete-input">Livro</label>
                    </div>
                    <div class="input-field">
                        <input type="text" name="title" id="title" value="<?=$var['info']['title']?>">
                        <label for="title">Titulo</label>
                    </div>
                    <div class="input-field">
                        <input type="text" name="text" id="text" value="<?=$var['info']['text']?>">
                        <label for="text">Texto</label>
                    </div>
                    <button class="btn waves-effect waves-light" type="submit">Salvar<i class="material-icons right">save</i></button>
                    <?php if (isset($_GET['text'])): ?>
                        <button class="btn waves-effect waves-light red" name="action" value="delete" type="submit">Remover<i class="material-icons right">delete</i></button>
                    <?php else: ?>
                        <button class="btn waves-effect waves-light red" disabled>Remover<i class="material-icons right">delete</i></button>
                    <?php endif ?>
                    <a href="/texto" class="btn waves-effect waves-light">Limpar<i class="material-icons right">clear</i></a>
                </form>
            </div>
        </div>
    </section>
</main>